### ISSUE TITLE
Error:Invalid DISPLAY variable

### ISSUE THREAD

**Issue by tianyu0523** [huybery/VisualizingCNN#1]
When I ran the code, this is an error in the following picture. Could you please help me solve it?
![_20180805083956](https://user-images.githubusercontent.com/25603473/43682948-3d7316a8-988b-11e8-9d35-c85a51920cfd.png)

**Comment by huybery** [comment]
Thanks for your issue. It seems that our operating environment is inconsistent.
You must declare `matplotlib.use('agg')` before import `matplotlib.pyplot as plt`. 
I just fixed it, you can update code using `git pull origin master`.
