### ISSUE TITLE
Question about 'conv2deconv_indices'

### ISSUE THREAD

**Issue by kevinlemon** [huybery/VisualizingCNN#2]
Hi huybery, thanks for your great work on VisualizingCNN.  
I am wondering why you use 'conv2dconv_indices' and 'unpool2pool_indices' in the 'vgg16_deconv.py'?  And how do you determine the values of them?

**Comment by huybery** [comment]
Deconv is the inverse process of conv,  so the last layer in conv is the first layer in deconv. You can find that sum of indices key and value is 30 which the total number of vgg components(conv, relu, pooling).

**Comment by kevinlemon** [comment]
Thank you for your reply. 
I understand it now. So, in 'init_weight' function in the 'vgg16_deconv.py', you want to initialize the weigth of deconv with the pretrained conv layers. And the key and value is the corresponding indices of each layers.  Am I right?

**Comment by huybery** [comment]
Yes, u are right. If there are no other questions, please close issue.
Thank you.
