### ISSUE TITLE
Visualise early layers and custom nets

### ISSUE THREAD

**Issue by cianeastwood** [huybery/VisualizingCNN#3]
Hello!

Very useful repo, thanks!

Just wondering if 

1. This has this worked well for units in the first few layers of any networks, e.g. VGG net? What does this look like for units in the first two layers?
2. This has worked for any smaller custom nets, e.g. for MNIST? I've edited my version of the code to allow for a small custom network for a colour MNIST dataset. While the colours are a bit off in all layers, the main issue is that after the first layer (i.e. a maxpool) all regions of the deconvolved image are effected (see image below). If you had to speculate, why might this happen for deconv?

![deconv_20](https://user-images.githubusercontent.com/8908376/77769164-5b938f80-703b-11ea-948b-99514ddfca92.png)

**Comment by huybery** [comment]
hello，thanks for your attention for this repo. 
Unfortunately, I can't answer your question exactly, you know, this is a classic paper, I just reproduced the details of the paper. 
In recent years, more and more good and easily visual convolution methods have emerged.
I hope you can get the answers you want to know from the recent paper.
